# Generated by Django 6.1 on 2026-09-14 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Método')),
                ('codigo', models.CharField(help_text='Código corto (ej: PM, EFECT)', max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('PAGO_MOVIL', 'Pago Móvil'), ('PUNTO_VENTA', 'Punto de Venta / Tarjeta'), ('DIVISA', 'Moneda Extranjera / Zelle / USDT'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20, verbose_name='Tipo de Método')),
                ('requiere_referencia', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'facturas_metodopago',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ingresostock',
            name='estado',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado')], default='PAGADO', max_length=10),
        ),
        migrations.AddField(
            model_name='ingresostock',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_origen', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to='facturacion.metodopago')),
            ],
            options={
                'verbose_name': 'Pago de Factura',
                'verbose_name_plural': 'Pagos de Facturas',
                'db_table': 'facturas_pagofactura',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_proveedor', to='facturacion.ingresostock')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.metodopago')),
            ],
            options={
                'db_table': 'compras_pagoproveedor',
            },
        ),
    ]
