# Generated by Django 6.1 on 2026-08-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_factura_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'permissions': [('sele_order', 'vista de ordenes de ventas')]},
        ),
    ]
