# Generated by Django 6.1 on 2026-08-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_factura_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_persona',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('J', 'J - Jurídico'), ('V', 'V - Venezolano'), ('E', 'E - Extranjero'), ('G', 'G - Gubernamental')], default='J', max_length=1),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_razon_social',
            field=models.CharField(max_length=150, verbose_name='Nombre / Razón Social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rif_cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='RIF / Cédula'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
