# Generated by Django 6.1 on 2026-08-27 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_proveedor_options_proveedor_contacto_persona_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tipo_documnento',
            new_name='TipoDocumento',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipo_documnento'),
        ),
    ]
